Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,3 +1,24 @@
+Skip to content
+Navigation Menu
+julien-onorato
+/
+T-POO-700-BDX_time-manager-backend
+
+Type / to search
+Code
+Issues
+Pull requests
+Actions
+Projects
+Wiki
+Security
+Insights
+CI/CD
+Update Dockerfile #15
+Jobs
+Run details
+Workflow file for this run
+.github/workflows/main.yml at 522342b
 name: CI/CD
  
 on:
@@ -48,50 +69,27 @@ jobs:
           VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
           VPS_HOST: ${{ secrets.VPS_HOST }}
         run: |
-         echo "${SSH_PRIVATE_KEY}" > key.pem
-         chmod 600 key.pem
-         # SSH into the VPS to execute Docker commands
-         ssh -o StrictHostKeyChecking=no -i key.pem ${VPS_USERNAME}@${VPS_HOST} << 'EOF'
-         
-         # Pull the latest Docker image
-         docker pull andydck/db:latest
-         docker pull andydck/backend:latest
-
-         # Stop and remove existing containers if they exist
-         # docker stop db_container || true
-         # docker rm db_container || true
-
-         # Stop and remove existing containers if they exist
-         # docker stop backend_container || true
-         # docker rm backend_container || true
-         
-         # Exécuter le conteneur de la base de données
-         docker run -d --name db_container \
-           -e POSTGRES_USER="postgres" \
-           -e POSTGRES_PASSWORD="root" \
-           -e POSTGRES_DB="time_manager_dev" \
-           -p 5432:5432 andydck/db:latest
-
-         
-         # Exécuter le conteneur du backend
-         docker run -d --name backend_container \
-           -e PGUSER="postgres" \
-           -e PGPASSWORD="root" \
-           -e PGDATABASE="time_manager_dev" \
-           -e PGHOST="db_container" \
-           -e PGPORT="5432" \
-           -p 4000:4000 andydck/backend:latest
-
-          # Créer la base de données
-         docker exec backend_container mix ecto.create
-
-         
-         # Optional: Wait for the container to start and check the status
-         sleep 10  # Give some time for the service to start
-         if docker ps | grep "backend"; then
-          echo "Service is up and running!"
-         else
-          echo "Service failed to start"
-          exit 1
-         fi
-         EOF
+          echo "${SSH_PRIVATE_KEY}" > key.pem
+          chmod 600 key.pem
+          ssh -o StrictHostKeyChecking=no -i key.pem ${VPS_USERNAME}@${VPS_HOST} << 'EOF'
+            cd ~/new_repo/T-POO-700-BDX_time-manager-backend/
+          
+            # Supprimer les container si besoin
+            docker compose down
+            
+            # Mettre à jour les fichiers depuis la branche main
+            git pull origin main
+          
+            # Démarrer les services Docker avec les fichiers à jour
+            docker compose up --build -d  # Build et démarrer les services en mode détaché
+          
+            sleep 10  # Attendre un peu pour que les services démarrent
+            docker compose ps  # Vérifier l'état des conteneurs
+          
+            if docker compose ps | grep "Up"; then
+              echo "Services are up and running!"
+            else
+              echo "Services failed to start"
+              exit 1
+            fi
+          EOF
