Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -52,5 +52,13 @@ jobs:
           chmod 600 key.pem
           ssh -o StrictHostKeyChecking=no -i key.pem ${VPS_USERNAME}@${VPS_HOST} << 'EOF'
             cd new_repo/T-POO-700-BDX_time-manager-backend/
-            docker compose up --build
+            docker compose up --build -d  # Run Docker Compose in detached mode
+            sleep 10  # Give some time for services to start
+            docker compose ps  # Check container status
+            if docker compose ps | grep "Up"; then
+             echo "Services are up and running!"
+            else
+             echo "Services failed to start"
+             exit 1
+            fi
           EOF
